#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

versions_dir=klotho-versions
mkdir -p "$versions_dir"

function klotho_ln() {
    rm -f klotho
    ln -s "$versions_dir/$1" klotho 
}

case "${1:-which}" in
  --version)
    if [[ ! -e klotho ]]; then
      echo "No klotho-which'ed klotho installed. See \"klotho-which help\""
      exit 1
    fi
    ONLY_PRINT_GIT_INFO=true ./klotho --version 2>&1 >/dev/null | cut -d' ' -f2
    ;;
  local/dev)
    klotho_ln run-local
    ;;
  release)
    if [[ "${2:-}" == latest || ! -f "$versions_dir/release" ]]; then
      [[ -f "$versions_dir/release" ]] && rm "$versions_dir/release"
      echo 
      printf 'Downloading latest klotho... '
      curl -fsSL "http://srv.klo.dev/update/latest/darwin/$(uname -m)" -o "$versions_dir/release"
      printf 'OK\n'
      chmod +x "$versions_dir/release"
    fi
    klotho_ln release
    ;;
  which)
    if [[ -h klotho ]]; then
      which_klotho="$(basename "$(stat -f %Y klotho)")"
      if [[ "$which_klotho" == run-local ]]; then
        KLOTHO_USE_SHOW_LINK=1 ./klotho
      else
        echo "$which_klotho"
      fi
    elif [[ -f klotho ]]; then
      echo >&2 "$pwd/klotho (not a symlink)"
      exit 2
    else
      echo >&2 'klotho not set up'
      exit 1
    fi
    ;;
  help)
    echo 'Provide "local/dev" or "release [latest]"'.
    echo 'You can also use just --version (without the positional arg) to print the active'
    echo "klotho's version, in a succinct format suitable for turning into file/dir paths."
    exit 1
    ;;
  *)
    echo "unrecognized option: $@"
    echo 'provide "local/dev" or "release"'
    exit 1
esac
