#!/bin/bash
set -euo pipefail

repo_dir="$( cd "$(dirname "$0")" ; echo "$PWD/klotho-versions/local/dev")"

if [[ -n "${KLOTHO_USE_SHOW_LINK-}" ]]; then
  echo 'local/dev'
  exit 0
fi


if [[ ! -d "$repo_dir" ]]; then
  echo >&2 "The following does not exist, or is not a directory: $repo_dir"
  echo >&2 ""
  echo >&2 "It must be klotho repo, or a symlink to one. Run:"
  echo >&2 ""
  echo >&2 "  ln -s ~/path/to/your/klotho $repo_dir"
  exit 1
fi

(
cd "$repo_dir"
git_info="$(git log --pretty=format:'%h' -n 1)"
if ! git diff --quiet ; then
  git_info="$git_info (dirty)"
fi
if [[ -n "${ONLY_PRINT_GIT_INFO-}" ]]; then
  echo >&2 "Version: local-$git_info"
  exit
fi

printf 'Installing %s...\r' "$git_info"
go generate ./... &>/dev/null
go install ./cmd/klotho
printf 'Using %s        \n' "$git_info"
)
if [[ -z "${ONLY_PRINT_GIT_INFO-}" ]]; then
  $(go env GOPATH)/bin/klotho "$@"
fi
